spring.application.name=payment_service
server.port=${SERVER_PORT}

spring.config.import=optional:file:.env[.properties]

spring.data.mongodb.uri=${MONGODB_URL}
spring.data.mongodb.auto-index-creation=true
logging.level.org.mongodb.driver=ERROR
logging.level.org.springframework.data.mongodb.core.MongoTemplate=ERROR

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.url=${MONGODB_URL}

random.number.api.url=${RANDOM_NUMBER_API_URL}
random.number.api.nuber.min=${RANDOM_NUMBER_API_MIN}
random.number.api.nuber.max=${RANDOM_NUMBER_API_MAX}
random.number.api.number.count=${RANDOM_NUMBER_API_NUMBER_COUNT}

